# Generated by Django 2.2 on 2019-06-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
